# https://rmoff.net/2018/08/02/kafka-listeners-explained/
version: '3.3'
services:

  # Queue - Zookeeper - KV storage for Kafka
  zookeeper:
    image: zookeeper:3.5.7
    restart: always
    hostname: zk
    container_name: zk
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
    volumes:
      - zkdata:/data
      - zkdatalog:/datalog

  # Kafka - stream processing engine
  kafka:
    image: confluentinc/cp-enterprise-kafka:5.4.3
    restart: "no"
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29094:29094
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_LISTENERS: LISTENER_INT://kafka:29092,LISTENER_EXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INT://kafka:29092,LISTENER_EXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INT
      KAFKA_HEAP_OPTS: "-Xmx512m -Xms512m"
    volumes:
      - kafdata:/var/lib/kafka

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - kafka

volumes:
  zkdata:
  zkdatalog:
  kafdata: